{ 'Clay at Battery': '41',
  'Davis at Jackson': '42',
  'Commercial at Montgomery': '45',
  'Washington at Kearney': '46',
  'Post at Kearney': '47',
  'Embarcadero at Vallejo': '48',
  'Spear at Folsom': '49',
  'Harry Bridges Plaza (Ferry Building)': '50',
  'Embarcadero at Folsom': '51',
  'Powell Street BART': '39',
  'Embarcadero at Bryant': '54',
  'Temporary Transbay Terminal (Howard at Beale)': '55',
  'Beale at Market': '56',
  '5th at Howard': '57',
  'San Francisco City Hall': '58',
  'Golden Gate at Polk': '59',
  'Embarcadero at Sansome': '60',
  '2nd at Townsend': '61',
  '2nd at Folsom': '62',
  'Howard at 2nd': '63',
  '2nd at South Park': '64',
  'Townsend at 7th': '65',
  'South Van Ness at Market': '66',
  'Market at 10th': '67',
  'Yerba Buena Center of the Arts (3rd @ Howard)': '68',
  'San Francisco Caltrain 2 (330 Townsend)': '69',
  'San Francisco Caltrain (Townsend at 4th)': '70',
  'Powell at Post (Union Square)': '71',
  'Civic Center BART (7th at Market)': '72',
  'Grant Avenue at Columbus Avenue': '73',
  'Steuart at Market': '74',
  'Mechanics Plaza (Market at Battery)': '75',
  'Market at 4th': '76',
  'Market at Sansome': '77',
  'Broadway St at Battery St': '82',
  '5th St at Folsom St': '90',
  'Cyril Magnin St at Ellis St': '91' }
